# Generated by Django 5.2.7 on 2025-11-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btick', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('view_own_bookings', 'Can view own bookings only'), ('cancel_own_booking', 'Can cancel own pending bookings'), ('view_event_bookings', 'Can view all bookings for managed events'), ('confirm_booking', 'Can confirm pending bookings'), ('refund_booking', 'Can refund/cancel any booking')], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('publish_event', 'Can publish draft events'), ('cancel_event', 'Can cancel events'), ('view_draft_events', 'Can view unpublished/draft events'), ('view_event_analytics', 'Can view event booking/sales analytics'), ('manage_event_tickets', 'Can manage event ticket tiers')], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventsticket',
            options={'permissions': [('view_ticket_inventory', 'Can view ticket inventory (quota/sold)'), ('adjust_ticket_quota', 'Can adjust ticket quota'), ('view_ticket_sales', 'Can view ticket sales metrics')], 'verbose_name': 'Events Ticket', 'verbose_name_plural': 'Events Tickets'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('view_own_organization', 'Can view own organization'), ('manage_organization_events', 'Can manage organization events'), ('view_organization_analytics', 'Can view organization analytics'), ('manage_organization_members', 'Can manage organization members')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'permissions': [('view_venue_schedule', 'Can view events scheduled at venue'), ('manage_venue_capacity', 'Can manage venue capacity'), ('view_venue_analytics', 'Can view venue analytics')], 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='btick.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization')],
            },
        ),
        migrations.CreateModel(
            name='VenueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_memberships', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='btick.venue')),
            ],
            options={
                'verbose_name': 'Venue Membership',
                'verbose_name_plural': 'Venue Memberships',
                'constraints': [models.UniqueConstraint(fields=('user', 'venue'), name='unique_user_venue')],
            },
        ),
    ]
