# Generated by Django 5.2.7 on 2025-10-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsticket',
            name='ticket_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('EARLY_BIRD', 'Early Bird'), ('STUDENT', 'Student'), ('GROUP', 'Group')], max_length=80),
        ),
    ]
