# Generated by Django 5.2.7 on 2025-12-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btick', '0002_alter_booking_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_quantity_ge_1',
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_ticket',
            field=models.ForeignKey(help_text='The specific ticket type being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='btick.eventsticket', verbose_name='Event ticket'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration time for pending bookings', null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of tickets in this booking', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status (PENDING, CONFIRMED, CANCELLED)', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='The user who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional override for venue capacity for this event', null=True, verbose_name='Event capacity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(help_text='The type/category of the event', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='btick.eventcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the event', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(help_text='Date and time when the event ends', verbose_name='End date/time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(help_text='The organization hosting this event', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='btick.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(help_text='Date and time when the event begins', verbose_name='Start date/time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current lifecycle status (DRAFT, PUBLISHED, CANCELLED)', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Unique title of the event', max_length=200, unique=True, verbose_name='Event title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(help_text='The location where the event takes place', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='btick.venue', verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text='Unique name of the event category', max_length=64, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='event',
            field=models.ForeignKey(help_text='The event this ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='btick.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per ticket in the default currency', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='Total number of tickets available for sale', verbose_name='Quota'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='sold',
            field=models.PositiveIntegerField(default=0, help_text='Number of tickets already sold', verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='ticket_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('EARLY_BIRD', 'Early Bird'), ('STUDENT', 'Student'), ('GROUP', 'Group')], help_text='The tier of the ticket (STANDARD, VIP, etc.)', max_length=80, verbose_name='Ticket type'),
        ),
        migrations.AlterField(
            model_name='eventsticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional email address for inquiries', max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Unique name of the organization', max_length=200, unique=True, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text="Optional URL to the organization's website", verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(help_text='The organization they belong to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='btick.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', help_text='Their role within the organization (OWNER, MANAGER, STAFF)', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, help_text='Optional physical address of the venue', max_length=500, verbose_name='Physical address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of attendees the venue can hold', verbose_name='Maximum capacity'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='Unique name of the venue', max_length=200, unique=True, verbose_name='Venue name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted (null if active)', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the record is active', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', help_text='Their role at the venue (MANAGER, STAFF)', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='venue_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='venuemembership',
            name='venue',
            field=models.ForeignKey(help_text='The venue they manage', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='btick.venue', verbose_name='Venue'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='booking_quantity_gte_1'),
        ),
    ]
