# Generated by Django 5.2.7 on 2025-11-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btick', '0002_alter_eventsticket_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='version',
        ),
        migrations.RemoveField(
            model_name='event',
            name='version',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='version',
        ),
        migrations.RemoveField(
            model_name='eventsticket',
            name='version',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='version',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='version',
        ),
    ]
